[package]
name = "d-shell"
version = "0.0.1"
edition = "2024"

[dependencies]
clearscreen = "4.0.6"
comfy-table = "7.2.2"
crossterm = "0.29.0"
inline_colorization = "0.1.6"
whoami = "2.1.2"
zip = "8.6.0"
d-shell-edit = {path="../d-shell-edit"}
d-shell-wasm = {path="../d-shell-wasm"}
reqwest = { version = "0.13.4", features = ["blocking"] }

[dev-dependencies]
tempfile = "3.19.1"
