[package]
name = "d-shell"
version = "0.1.0"
edition = "2024"

[dependencies]
clearscreen = "4.0.6"
comfy-table = "7.2.2"
crossterm = "0.29.0"
inline_colorization = "0.1.6"
whoami = "2.1.2"
zip = "8.6.0"
wasmtime = "46.0.1"
wasmtime-wasi = "46.0.1"
mlua = { version = "0.12.0", features = ["luau", "vendored"] }
ggez = "0.10.0"
d-shell-edit = {path="../d-shell-edit"}

[dev-dependencies]
tempfile = "3.19.1"
